# nixy listening port
port = "6000"
# optional X-Proxy header name
xproxy = "hostname"
# marathon api
marathon = ["http://example01:8080", "http://example02:8080"] # add all HA cluster nodes in priority order.
user = "" # leave empty if no auth is required.
pass = ""
# nginx
nginx_config = "/etc/nginx/nginx.conf"
nginx_template = "/etc/nginx/nginx.tmpl"
nginx_cmd = "nginx" # optinally openresty
# statsd settings
statsd = "localhost:8125" # optional for statistics
